### PR TITLE
Rename fast-farm-card.js to fast-farm-card.user.js

### PR DESCRIPTION
**Pull request by MonkAlex**
https://wiki.greasespot.net/Greasemonkey_Manual:Installing_Scripts

File must be end with `.user.js`

### CODE REVIEW

**Comment by MonkAlex** [comment]
So, with this changes all link alive.

**Review by Kasp42 — COMMENTED** [review]
Comment

**Review by Kasp42 — COMMENTED** [review]
Comment

**Review by Kasp42 — COMMENTED** [review]
Comment

**Review by Kasp42 — CHANGES_REQUESTED** [review]
Comment

**Review by Kasp42 — APPROVED** [review]

**Review by Kasp42 — APPROVED** [review]
Comment

**Review by Kasp42 — APPROVED** [review]
Comment

**Pull request merged**
